// backend/src/ai/modelRegistry.js
/**
 * Model Registry
 * Central source of truth for the 4 PRABHA models.
 * Defines the required features and dataset IDs for each mode.
 */

const PREDICTION_MODES = {
  SYMPTOMS_ONLY: "symptoms_only",
  BLOOD_TEST: "blood_test",
  ULTRASOUND: "ultrasound",
  COMBINED: "combined",
};

const MODELS = {
  [PREDICTION_MODES.SYMPTOMS_ONLY]: {
    id: "RF_Model_1_Dataset_1",
    description: "Symptoms Only Model",
    features: [
      "Age (yrs)",
      "Weight (Kg)",
      "Height(Cm)",
      "BMI",
      "Cycle(R/I)",
      "Cycle length(days)",
      "Hip(inch)",
      "Waist(inch)",
      "Waist:Hip Ratio",
      "Weight gain(Y/N)",
      "hair growth(Y/N)",
      "Skin darkening (Y/N)",
      "Hair loss(Y/N)",
      "Pimples(Y/N)",
      "Fast food (Y/N)",
      "Reg.Exercise(Y/N)",
    ],
  },
  [PREDICTION_MODES.BLOOD_TEST]: {
    id: "RF_Model_2_Dataset_2",
    description: "Symptoms + Blood Test Model",
    features: [
      "Age (yrs)",
      "Weight (Kg)",
      "Height(Cm)",
      "BMI",
      "Blood Group",
      "Pulse rate(bpm)",
      "RR (breaths/min)",
      "Hb(g/dl)",
      "Cycle(R/I)",
      "Cycle length(days)",
      "FSH(mIU/mL)",
      "LH(mIU/mL)",
      "LH:FSH",
      "FSH/LH",
      "Hip(inch)",
      "Waist(inch)",
      "Waist:Hip Ratio",
      "TSH (mIU/L)",
      "AMH(ng/mL)",
      "PRL(ng/mL)",
      "Vit D3 (ng/mL)",
      "PRG(ng/mL)",
      "RBS(mg/dl)",
      "Weight gain(Y/N)",
      "hair growth(Y/N)",
      "Skin darkening (Y/N)",
      "Hair loss(Y/N)",
      "Pimples(Y/N)",
      "Fast food (Y/N)",
      "Reg.Exercise(Y/N)",
      "BP _Systolic (mmHg)",
      "BP _Diastolic (mmHg)",
    ],
  },
  [PREDICTION_MODES.ULTRASOUND]: {
    id: "RF_Model_3_Dataset_3",
    description: "Symptoms + Ultrasound Model",
    features: [
      "Age (yrs)",
      "Weight (Kg)",
      "Height(Cm)",
      "BMI",
      "Cycle(R/I)",
      "Cycle length(days)",
      "Hip(inch)",
      "Waist(inch)",
      "Waist:Hip Ratio",
      "Weight gain(Y/N)",
      "hair growth(Y/N)",
      "Skin darkening (Y/N)",
      "Hair loss(Y/N)",
      "Pimples(Y/N)",
      "Fast food (Y/N)",
      "Reg.Exercise(Y/N)",
      "Follicle No. (L)",
      "Follicle No. (R)",
      "Avg. F size (L) (mm)",
      "Avg. F size (R) (mm)",
      "Endometrium (mm)",
    ],
  },
  [PREDICTION_MODES.COMBINED]: {
    id: "RF_Model_4_Dataset_4",
    description: "Combined Model (Symptoms + Blood + Ultrasound)",
    features: [
      "Age (yrs)",
      "Weight (Kg)",
      "Height(Cm)",
      "BMI",
      "Blood Group",
      "Pulse rate(bpm)",
      "RR (breaths/min)",
      "Hb(g/dl)",
      "Cycle(R/I)",
      "Cycle length(days)",
      "FSH(mIU/mL)",
      "LH(mIU/mL)",
      "LH:FSH",
      "FSH/LH",
      "Hip(inch)",
      "Waist(inch)",
      "Waist:Hip Ratio",
      "TSH (mIU/L)",
      "AMH(ng/mL)",
      "PRL(ng/mL)",
      "Vit D3 (ng/mL)",
      "PRG(ng/mL)",
      "RBS(mg/dl)",
      "Weight gain(Y/N)",
      "hair growth(Y/N)",
      "Skin darkening (Y/N)",
      "Hair loss(Y/N)",
      "Pimples(Y/N)",
      "Fast food (Y/N)",
      "Reg.Exercise(Y/N)",
      "BP _Systolic (mmHg)",
      "BP _Diastolic (mmHg)",
      "Follicle No. (L)",
      "Follicle No. (R)",
      "Avg. F size (L) (mm)",
      "Avg. F size (R) (mm)",
      "Endometrium (mm)",
    ],
  },
};

export { PREDICTION_MODES, MODELS };
